{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <main.TestClass object at 0x7fd73f265f40>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nmain.py:12: AssertionError"}, "start": 1653226886646, "stop": 1653226886646, "uuid": "05b492c7-c21a-4b42-b54d-dec17b1415ce", "historyId": "030ffa2029208efe12175abafefdc616", "testCaseId": "81302df1bab4ec9cede73a9016a7b47a", "fullName": "main.TestClass#test_two", "labels": [{"name": "suite", "value": "main"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "bran-t14"}, {"name": "thread", "value": "53279-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}