{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <main.TestClass object at 0x7f9508271d60>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nmain.py:12: AssertionError"}, "start": 1653466879434, "stop": 1653466879434, "uuid": "0b4681a1-fa1a-4ea3-ae9f-430a1c8346d6", "historyId": "030ffa2029208efe12175abafefdc616", "testCaseId": "81302df1bab4ec9cede73a9016a7b47a", "fullName": "main.TestClass#test_two", "labels": [{"name": "suite", "value": "main"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "bran-t14"}, {"name": "thread", "value": "21056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}